### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by kaelig** [sass-mq/sass-mq#61]
Tests are running locally with success but it looks like there is an issue with the latest version of [Eyeglass](https://github.com/sass-eyeglass/eyeglass) when running on Travis, see:
https://travis-ci.org/sass-mq/sass-mq/builds/73874507

Stacktrace:

```
/home/travis/build/sass-mq/sass-mq/node_modules/eyeglass/node_modules/node-sass-utils/lib/sass_js_map.js:168
  SassJsMap.prototype[Symbol.iterator] = function() {
                      ^
ReferenceError: Symbol is not defined
    at module.exports (/home/travis/build/sass-mq/sass-mq/node_modules/eyeglass/node_modules/node-sass-utils/lib/sass_js_map.js:168:23)
    at module.exports (/home/travis/build/sass-mq/sass-mq/node_modules/eyeglass/node_modules/node-sass-utils/lib/index.js:185:45)
    at module.exports (/home/travis/build/sass-mq/sass-mq/node_modules/eyeglass/lib/assets.js:206:45)
    at Object.Eyeglass (/home/travis/build/sass-mq/sass-mq/node_modules/eyeglass/lib/index.js:17:36)
    at Object.<anonymous> (/home/travis/build/sass-mq/sass-mq/test/eyeglass-test.js:11:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
travis_time:end:1d428ac1:start=1438601025365766669,finish=1438601025935514225,duration=569747556
```

**Comment by kaelig** [comment]
@chriseppstein is this an error you've seen before?

**Comment by kaelig** [comment]
Thanks to @chriseppstein for fixing node-sass-utils in https://travis-ci.org/sass-mq/sass-mq/builds/73874507
